server.port=8080
server.servlet.context-path=/ElectroInternal
# configure datasource
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
# jpa configs (optional )
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# disable validation in the persistence layer
spring.jpa.properties.jakarta.persistence.validation.mode=none
remember.me.key=${REMEMBER_ME_KEY}
app.user-photos.path=${USER_PHOTOS_PATH}
app.category-images.path=${CATEGORY_IMAGES_PATH}
app.brand-logos.path=${BRAND_LOGOS_PATH}
app.product-images.path=${PRODUCT_IMAGES_PATH}
app.default-images.path=${DEFAULT_IMAGES_PATH}